"""ViVeSec AI Box - local RAG PoC CLI.

Subcommands:
  info    show backend status (Ollama? models? embedding/LLM backend)
  ingest  build the local index from poc/data/*.txt
  ask     one-shot query or slash command  (e.g. ask "/legal termination risks")
  chat    interactive REPL
  bench   measure generation tok/s on Ollama (or print published references)
"""
import argparse
import sys
import time

import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import config
import embeddings
import llm
import ollama_client as ollama
import rag

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

PROV = "Searched 100% locally on ViVeSecBox"


def cmd_info(args):
    up = ollama.available()
    print("ViVeSec AI Box - PoC environment")
    print("  Ollama URL        :", config.OLLAMA_URL)
    print("  Ollama running    :", up)
    if up:
        print("  Models pulled     :", ", ".join(ollama.list_models()) or "(none)")
    print("  Gen model (target):", config.GEN_MODEL)
    print("  Embed model       :", config.EMBED_MODEL)
    if config.ANSWER_LANG:
        print("  Answer language   :", config.ANSWER_LANG)
    print("  Embed backend     :", embeddings.backend_name(embeddings.use_ollama_embed()))
    print("  LLM backend       :", "ollama:" + config.GEN_MODEL if llm.use_ollama_gen() else "fallback:extractive")


def cmd_ingest(args):
    meta, files = rag.ingest()
    print("Ingested %d source(s), %d chunk(s)." % (meta["n_sources"], meta["n_chunks"]))
    print("Embedding backend:", meta["embed_backend"])
    for f in files:
        print("  +", f)
    print("Index:", config.INDEX_PATH)


def _print_result(res):
    if "error" in res:
        print(res["error"])
        return
    print("Command: %s  |  %s  |  %s" % (res["command"], res["label"], res["mode"]))
    if res.get("answer"):
        print("\n" + res["answer"] + "\n")
        print("Generated by:", res.get("llm_backend"))
    print("\nSources:")
    print(rag.format_citations(res["hits"]))
    print("\n%s - %s | %d chunks indexed." % (
        PROV, ", ".join(res["sources"]), res["meta"].get("n_chunks", 0)))


def cmd_ask(args):
    _print_result(rag.answer(args.query))


def cmd_chat(args):
    print("ViVeSec PoC chat. Ask a question or use a slash command")
    print("(/search /summary /report /memo /legal /finance /compliance /hr). Ctrl+C to exit.")
    while True:
        try:
            q = input("\nvivesec> ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nbye")
            break
        if not q:
            continue
        if q in ("/exit", "/quit"):
            break
        _print_result(rag.answer(q))


def cmd_bench(args):
    if not ollama.available():
        print("Ollama not running. Published Jetson Orin Nano Super INT4 references (tok/s):")
        print("  Llama 3.2 3B = 43 | Phi 3.5 = 38 | Gemma2 2B = 35 | Qwen2.5 7B = 22 | Llama3.1 8B = 19")
        print("Install Ollama and pull the model to measure on your own hardware.")
        return
    prompt = "Write a 120-word executive summary about secure offline enterprise AI."
    t0 = time.time()
    content, ec, ed = ollama.chat("You are concise.", prompt, model=args.model)
    wall = time.time() - t0
    if ec and ed:
        print("model=%s  eval_count=%d  eval_time=%.2fs  ->  %.1f tok/s (server-measured)" % (
            args.model, ec, ed / 1e9, ec / (ed / 1e9)))
    print("wall=%.2fs  chars=%d" % (wall, len(content)))


def main():
    p = argparse.ArgumentParser(prog="vivesec-poc", description="ViVeSec AI Box local RAG PoC")
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("info").set_defaults(func=cmd_info)
    sub.add_parser("ingest").set_defaults(func=cmd_ingest)
    a = sub.add_parser("ask")
    a.add_argument("query")
    a.set_defaults(func=cmd_ask)
    sub.add_parser("chat").set_defaults(func=cmd_chat)
    b = sub.add_parser("bench")
    b.add_argument("--model", default=config.GEN_MODEL)
    b.set_defaults(func=cmd_bench)
    args = p.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
