"""Run a gold-set against one engine and produce per-case + aggregate results.

A "run" = ingest the fixture corpus, then for each gold case issue the exact
`/rag/search_context` the híd would — scoped to the corpus(es) of the case's
`allowed_file_ids` HARD pre-filter — score the response, and aggregate. The
corpus boundary IS the ACL pre-filter, so the harness exercises the v1
isolation model directly. Hits are attributed to file_ids via `source_path`
(multi-file drive corpora); a hit whose path is unknown resolves to a sentinel
and therefore counts as a leak — fail-closed. The gold-set is split
dev/holdout to fight overfitting (tune on dev, REPORT on holdout).

Profiles: SMOKE (fixtures/, dev|holdout.jsonl) and FULL (fixtures_full/,
dev_full|holdout_full.jsonl, generated by gen_corpus.py).
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass

from client import EngineClient
from corpus import (
    FIXTURES_DIR,
    TENANT,
    build_corpus_map,
    build_file_to_corpus,
    build_path_map,
    ingest_corpus,
)
from metrics import Aggregate, CaseResult, aggregate, score_case

HERE = os.path.dirname(os.path.abspath(__file__))
GOLD_DIR = os.path.join(HERE, "gold_set")

MAX_CONTEXT_TOKENS = 4000


def load_gold(split: str, suffix: str = "") -> list[dict]:
    """split: 'dev' | 'holdout' (+ optional profile suffix, e.g. '_full')."""
    path = os.path.join(GOLD_DIR, f"{split}{suffix}.jsonl")
    cases: list[dict] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("//"):
                cases.append(json.loads(line))
    return cases


@dataclass
class RunReport:
    engine_name: str
    engine_version: str
    split: str
    use_chunks: bool
    cases: list[CaseResult]
    agg: Aggregate


def _norm(path: str) -> str:
    if path and len(path) > 1 and path.endswith("/"):
        return path.rstrip("/")
    return path


def run_engine(
    client: EngineClient,
    split: str = "dev",
    top_k: int = 5,
    use_chunks: bool = False,
    do_ingest: bool = True,
    fixtures_dir: str = FIXTURES_DIR,
    gold_suffix: str = "",
) -> RunReport:
    if do_ingest:
        ingest_corpus(client, fixtures_dir)

    corpus_to_file = build_corpus_map(fixtures_dir)
    file_to_corpus = build_file_to_corpus(fixtures_dir)
    path_to_file = build_path_map(fixtures_dir)

    health = client.health()
    engine_name = health.get("vector_backend", "?")
    emb = health.get("embedding", {}) or {}
    engine_version = f"{emb.get('model_name', '?')}/{emb.get('dimension', '?')}d"

    gold = load_gold(split, gold_suffix)
    results: list[CaseResult] = []
    for case in gold:
        question = case["query"]
        allowed = case.get("allowed_file_ids", [])
        # Deduplicate: in the drive model many allowed files share one corpus.
        allowed_corpora: list[str] = []
        for fid in allowed:
            cid = file_to_corpus.get(fid)
            if cid and cid not in allowed_corpora:
                allowed_corpora.append(cid)
        merged_hits: list[dict] = []
        wall_total = 0.0
        # Query each ALLOWED corpus; corpus isolation = the ACL pre-filter. A
        # hit is attributed to a file via its source_path; unknown paths fall
        # back to the corpus map and finally to a sentinel that can never be in
        # `allowed` — so an unattributable hit counts as a leak (fail-closed).
        for corpus_id in allowed_corpora:
            response, wall_ms = client.search_context(
                {
                    "corpus_id": corpus_id,
                    "tenant_id": TENANT,
                    "question": question,
                    "top_k": top_k,
                    "max_context_tokens": MAX_CONTEXT_TOKENS,
                }
            )
            wall_total += wall_ms
            for ctx in response.get("contexts", []):
                src = _norm(ctx.get("source_path", "") or "")
                fid = path_to_file.get(src) or corpus_to_file.get(corpus_id) \
                    or f"unresolved://{corpus_id}{src}"
                merged_hits.append(
                    {
                        "file_id": fid,
                        "chunk_id": ctx.get("chunk_id", ""),
                        "doc_id": ctx.get("doc_id", ""),
                        "score": float(ctx.get("score") or 0.0),
                        "source_path": ctx.get("source_path", ""),
                        "snippet": (ctx.get("text") or "")[:240],
                    }
                )
        merged_hits.sort(key=lambda h: h["score"], reverse=True)
        merged_hits = merged_hits[:top_k]
        results.append(score_case(case, {"hits": merged_hits}, wall_total, use_chunks))

    return RunReport(
        engine_name=engine_name,
        engine_version=engine_version,
        split=split,
        use_chunks=use_chunks,
        cases=results,
        agg=aggregate(results),
    )


def print_run(report: RunReport) -> None:
    a = report.agg
    print(f"== {report.engine_name} v{report.engine_version}  [{report.split}]  n={a.n} ==")
    print(f"  recall@k     : {a.recall_at_k:.3f}")
    print(f"  precision@k  : {a.precision_at_k:.3f}")
    print(f"  MRR          : {a.mrr:.3f}")
    print(f"  citation rate: {a.citation_rate:.3f}")
    print(f"  ACL leaks    : {a.acl_leak_total}  ({'OK' if a.acl_leak_total == 0 else 'FAIL'})")
    print(f"  latency p50  : {a.latency_p50_ms:.0f} ms")
    print(f"  latency p95  : {a.latency_p95_ms:.0f} ms")
    leaking = [c.case_id for c in report.cases if c.acl_leaks]
    if leaking:
        print(f"  !! leaking cases: {', '.join(leaking)}")
